spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/difman_mini?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: c2619zz
    password: kgyqpt123^^
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://difmanmini.c0jozjhm0fyf.ap-northeast-2.rds.amazonaws.com:3306/c2619zz?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org:
      hibernate: debug
